import { Park, ParkCategory, LandscapeType } from './types';

export const THEME_COLOR_PRIMARY = '#2A6E3F'; // Cyan Green
export const THEME_COLOR_SECONDARY = '#2F3D4C'; // Ink Dark
export const THEME_COLOR_ACCENT = '#C84B31'; // Seal Red

export const PARKS_DATA: Park[] = [
  {
    id: '1',
    name: '三江源国家公园',
    location: '青海',
    description: '长江、黄河、澜沧江的发源地，中华水塔，高寒生态系统的典型代表。',
    category: ParkCategory.NATIONAL_PARK,
    landscapes: [LandscapeType.WETLAND, LandscapeType.MOUNTAIN, LandscapeType.RIVER_LAKE, LandscapeType.ANIMAL],
    imageUrl: 'https://picsum.photos/id/1036/800/600',
    rating: 5.0,
    openTime: '全天 (特许进入)',
    ticketInfo: '需预约特许',
    transportInfo: '玉树机场包车',
    weatherInfo: '高寒缺氧，夏季凉爽',
    poetry: '君不见黄河之水天上来，奔流到海不复回。',
    bestSeason: '7-8月',
    crowdLevel: '舒适',
    seasonColor: '#8ABCD1',
    seasonColorName: '天青'
  },
  {
    id: '2',
    name: '大熊猫国家公园',
    location: '四川/陕西/甘肃',
    description: '横跨三省，保护国宝大熊猫及其伞护的生物多样性。',
    category: ParkCategory.NATIONAL_PARK,
    landscapes: [LandscapeType.FOREST, LandscapeType.ANIMAL],
    imageUrl: 'https://picsum.photos/id/1003/800/600',
    rating: 4.9,
    openTime: '08:00 - 17:00',
    ticketInfo: '核心区禁入，周边58元起',
    transportInfo: '成都高铁直达',
    weatherInfo: '湿润多雨',
    poetry: '竹深树密虫鸣处，时有微凉不是风。',
    bestSeason: '9-11月',
    crowdLevel: '适中',
    seasonColor: '#4A6E46',
    seasonColorName: '竹青'
  },
  {
    id: '3',
    name: '武夷山国家公园',
    location: '福建',
    description: '世界文化与自然双重遗产，丹霞地貌与理学文化交融。',
    category: ParkCategory.NATIONAL_PARK,
    landscapes: [LandscapeType.MOUNTAIN, LandscapeType.RIVER_LAKE, LandscapeType.FOREST],
    imageUrl: 'https://picsum.photos/id/1043/800/600',
    rating: 4.8,
    openTime: '07:30 - 17:30',
    ticketInfo: '主景区140元',
    transportInfo: '武夷山北站直达',
    weatherInfo: '夏季炎热，春秋宜人',
    poetry: '武夷山上有仙灵，山下寒流曲曲清。',
    bestSeason: '4-11月',
    crowdLevel: '适中',
    seasonColor: '#D15842',
    seasonColorName: '丹砂'
  },
  {
    id: '4',
    name: '黄山风景区',
    location: '安徽',
    description: '五岳归来不看山，黄山归来不看岳。奇松怪石云海温泉冬雪。',
    category: ParkCategory.WORLD_HERITAGE,
    landscapes: [LandscapeType.MOUNTAIN, LandscapeType.FOREST],
    imageUrl: 'https://picsum.photos/id/1018/800/600',
    rating: 4.9,
    openTime: '06:00 - 17:30',
    ticketInfo: '旺季190元',
    transportInfo: '黄山北站',
    weatherInfo: '云雾多变',
    poetry: '三十六峰高插天，瑶台琼宇贮神仙。',
    bestSeason: '四季皆宜',
    crowdLevel: '拥挤',
    seasonColor: '#F0E68C',
    seasonColorName: '松花'
  },
  {
    id: '5',
    name: '九寨沟自然保护区',
    location: '四川',
    description: '童话世界，九寨归来不看水。钙华湖泊群与彩林。',
    category: ParkCategory.NATURE_RESERVE,
    landscapes: [LandscapeType.RIVER_LAKE, LandscapeType.FOREST, LandscapeType.MOUNTAIN],
    imageUrl: 'https://picsum.photos/id/1039/800/600',
    rating: 5.0,
    openTime: '07:30 - 17:00',
    ticketInfo: '旺季190+90元',
    transportInfo: '九黄机场',
    weatherInfo: '高原气候',
    poetry: '瑶池本是在人间，堪笑求仙错问天。',
    bestSeason: '10月',
    crowdLevel: '拥挤',
    seasonColor: '#008B8B',
    seasonColorName: '石青'
  },
  {
    id: '6',
    name: '桂林山水(漓江)',
    location: '广西',
    description: '典型的喀斯特地貌，山青水秀洞奇石美。',
    category: ParkCategory.SCENIC_5A,
    landscapes: [LandscapeType.KARST, LandscapeType.RIVER_LAKE],
    imageUrl: 'https://picsum.photos/id/1025/800/600',
    rating: 4.8,
    openTime: '全天',
    ticketInfo: '游船约200元',
    transportInfo: '桂林两江机场',
    weatherInfo: '亚热带季风',
    poetry: '江作青罗带，山如碧玉簪。',
    bestSeason: '4-10月',
    crowdLevel: '适中',
    seasonColor: '#6B8E23',
    seasonColorName: '柳绿'
  },
  {
    id: '7',
    name: '张家界国家森林公园',
    location: '湖南',
    description: '独特的石英砂岩峰林地貌，阿凡达哈利路亚山原型。',
    category: ParkCategory.WORLD_HERITAGE,
    landscapes: [LandscapeType.MOUNTAIN, LandscapeType.FOREST],
    imageUrl: 'https://picsum.photos/id/1035/800/600',
    rating: 4.8,
    openTime: '07:00 - 18:00',
    ticketInfo: '门票224元',
    transportInfo: '荷花机场',
    weatherInfo: '湿润多雾',
    poetry: '奇峰三千，秀水八百。',
    bestSeason: '4-10月',
    crowdLevel: '拥挤',
    seasonColor: '#556B2F',
    seasonColorName: '葱倩'
  },
  {
    id: '8',
    name: '长白山自然保护区',
    location: '吉林',
    description: '休眠火山，拥有壮观的天池和垂直植被带。',
    category: ParkCategory.NATURE_RESERVE,
    landscapes: [LandscapeType.MOUNTAIN, LandscapeType.FOREST, LandscapeType.RIVER_LAKE],
    imageUrl: 'https://picsum.photos/id/1020/800/600',
    rating: 4.8,
    openTime: '08:00 - 16:30',
    ticketInfo: '北坡105+85元',
    transportInfo: '长白山机场',
    weatherInfo: '冬季严寒',
    poetry: '千年积雪万年松，直上人间第一峰。',
    bestSeason: '7-9月, 1-2月',
    crowdLevel: '适中',
    seasonColor: '#F5F5F5',
    seasonColorName: '精白'
  },
  {
    id: '9',
    name: '海南热带雨林国家公园',
    location: '海南',
    description: '中国保存最完好、连片面积最大的大陆性岛屿型热带雨林。',
    category: ParkCategory.NATIONAL_PARK,
    landscapes: [LandscapeType.FOREST, LandscapeType.ANIMAL],
    imageUrl: 'https://picsum.photos/id/1019/800/600',
    rating: 4.7,
    openTime: '08:00 - 17:30',
    ticketInfo: '各分景区不同',
    transportInfo: '海口/三亚转大巴',
    weatherInfo: '热带海洋气候',
    poetry: '一去一万里，千之千不还。',
    bestSeason: '11-4月',
    crowdLevel: '舒适',
    seasonColor: '#228B22',
    seasonColorName: '翠微'
  },
  {
    id: '10',
    name: '珠穆朗玛峰保护区',
    location: '西藏',
    description: '世界之巅，极高山生态系统，壮丽的冰川和雪山。',
    category: ParkCategory.NATURE_RESERVE,
    landscapes: [LandscapeType.GLACIER, LandscapeType.MOUNTAIN],
    imageUrl: 'https://picsum.photos/id/1038/800/600',
    rating: 4.9,
    openTime: '全天',
    ticketInfo: '进山费180元+环保车',
    transportInfo: '日喀则包车',
    weatherInfo: '严寒大风',
    poetry: '会当凌绝顶，一览众山小。',
    bestSeason: '4-5月, 9-10月',
    crowdLevel: '舒适',
    seasonColor: '#FFFFFF',
    seasonColorName: '皎玉'
  }
];

export const REGIONS = [
  { name: '西北', color: '#E0C89F' },
  { name: '西南', color: '#88A090' },
  { name: '华北/东北', color: '#A8B8C8' },
  { name: '华东/华中', color: '#90A088' },
  { name: '华南', color: '#609078' }
];

export const INTEREST_TAGS = ['摄影', '徒步', '亲子', '研学', '观鸟', '露营', '人文', '自驾'];
